name: Go

on:
  push:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Generate build files
        uses: jozo/go-cross-build@patch-1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'simple-pomodoro'
            compress: 'false'
            dest: 'dist'
