name: Go

on:
  push:
    branches: [ master ]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y libgl1-mesa-dev xorg-dev libasound2-dev

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - run: go version
        
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Build the app
        run: make build
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Simple Pomodoro.tar.xz
