name: Build MacOS binary

on: workflow_dispatch

jobs:
  generate:
    name: Generate MacOS build
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - run: go version
        
      - name: Install dependencies
        run: sudo apt install -y libgl1-mesa-dev xorg-dev libasound2-dev

      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Build the app
        run: |
          go get fyne.io/fyne/v2/cmd/fyne
          go build -ldflags "-s -w"
          ls -la
          tar -cvf simple-pomodoro.tar ./simple-pomodoro.app
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: simple-pomodoro
          path: ./simple-pomodoro.tar
