name: Build Windows binary

on: workflow_dispatch

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - run: go version
      
      - name: Instal GCC compilers
        uses: msys2/setup-msys2@v2
        
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Build the app
        run: |
          go get fyne.io/fyne/v2/cmd/fyne
          make pack
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: simple-pomodoro.windows
          path: ./Simple Pomodoro.exe
